"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

palette = "rose-pine"

add_newline = true

[character]
success_symbol = " [●](bold rose)"
error_symbol = " [●](bold love)"
vimcmd_symbol = " [●](bold foam)"
vimcmd_replace_one_symbol = " ●"
vimcmd_replace_symbol = " ●"
vimcmd_visual_symbol = " ●"


[directory]
format = "[ $path ]($style)"
style = "fg:rose"
truncation_length = 3
truncation_symbol = "/"

[git_branch]
symbol = ""
format = '[$symbol $branch]($style) '
style = "fg:#6e6a86"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "fg:foam"

[fill]
symbol = " "

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
subtle = '#908caa'
